/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TablaRouteImport } from './routes/tabla'
import { Route as PracticaRouteImport } from './routes/practica'
import { Route as ParcheRouteImport } from './routes/parche'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as DecisionRouteImport } from './routes/decision'
import { Route as CheatSheetRouteImport } from './routes/cheat-sheet'
import { Route as BorradorGlassRouteImport } from './routes/borrador-glass'
import { Route as BlueTeamRouteImport } from './routes/blue-team'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EscEscIdRouteImport } from './routes/esc.$escId'

const TablaRoute = TablaRouteImport.update({
  id: '/tabla',
  path: '/tabla',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticaRoute = PracticaRouteImport.update({
  id: '/practica',
  path: '/practica',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcheRoute = ParcheRouteImport.update({
  id: '/parche',
  path: '/parche',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionRoute = DecisionRouteImport.update({
  id: '/decision',
  path: '/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatSheetRoute = CheatSheetRouteImport.update({
  id: '/cheat-sheet',
  path: '/cheat-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const BorradorGlassRoute = BorradorGlassRouteImport.update({
  id: '/borrador-glass',
  path: '/borrador-glass',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueTeamRoute = BlueTeamRouteImport.update({
  id: '/blue-team',
  path: '/blue-team',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EscEscIdRoute = EscEscIdRouteImport.update({
  id: '/esc/$escId',
  path: '/esc/$escId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blue-team': typeof BlueTeamRoute
  '/borrador-glass': typeof BorradorGlassRoute
  '/cheat-sheet': typeof CheatSheetRoute
  '/decision': typeof DecisionRoute
  '/mapa': typeof MapaRoute
  '/parche': typeof ParcheRoute
  '/practica': typeof PracticaRoute
  '/tabla': typeof TablaRoute
  '/esc/$escId': typeof EscEscIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blue-team': typeof BlueTeamRoute
  '/borrador-glass': typeof BorradorGlassRoute
  '/cheat-sheet': typeof CheatSheetRoute
  '/decision': typeof DecisionRoute
  '/mapa': typeof MapaRoute
  '/parche': typeof ParcheRoute
  '/practica': typeof PracticaRoute
  '/tabla': typeof TablaRoute
  '/esc/$escId': typeof EscEscIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blue-team': typeof BlueTeamRoute
  '/borrador-glass': typeof BorradorGlassRoute
  '/cheat-sheet': typeof CheatSheetRoute
  '/decision': typeof DecisionRoute
  '/mapa': typeof MapaRoute
  '/parche': typeof ParcheRoute
  '/practica': typeof PracticaRoute
  '/tabla': typeof TablaRoute
  '/esc/$escId': typeof EscEscIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blue-team'
    | '/borrador-glass'
    | '/cheat-sheet'
    | '/decision'
    | '/mapa'
    | '/parche'
    | '/practica'
    | '/tabla'
    | '/esc/$escId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blue-team'
    | '/borrador-glass'
    | '/cheat-sheet'
    | '/decision'
    | '/mapa'
    | '/parche'
    | '/practica'
    | '/tabla'
    | '/esc/$escId'
  id:
    | '__root__'
    | '/'
    | '/blue-team'
    | '/borrador-glass'
    | '/cheat-sheet'
    | '/decision'
    | '/mapa'
    | '/parche'
    | '/practica'
    | '/tabla'
    | '/esc/$escId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlueTeamRoute: typeof BlueTeamRoute
  BorradorGlassRoute: typeof BorradorGlassRoute
  CheatSheetRoute: typeof CheatSheetRoute
  DecisionRoute: typeof DecisionRoute
  MapaRoute: typeof MapaRoute
  ParcheRoute: typeof ParcheRoute
  PracticaRoute: typeof PracticaRoute
  TablaRoute: typeof TablaRoute
  EscEscIdRoute: typeof EscEscIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tabla': {
      id: '/tabla'
      path: '/tabla'
      fullPath: '/tabla'
      preLoaderRoute: typeof TablaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practica': {
      id: '/practica'
      path: '/practica'
      fullPath: '/practica'
      preLoaderRoute: typeof PracticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parche': {
      id: '/parche'
      path: '/parche'
      fullPath: '/parche'
      preLoaderRoute: typeof ParcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision': {
      id: '/decision'
      path: '/decision'
      fullPath: '/decision'
      preLoaderRoute: typeof DecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheat-sheet': {
      id: '/cheat-sheet'
      path: '/cheat-sheet'
      fullPath: '/cheat-sheet'
      preLoaderRoute: typeof CheatSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrador-glass': {
      id: '/borrador-glass'
      path: '/borrador-glass'
      fullPath: '/borrador-glass'
      preLoaderRoute: typeof BorradorGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blue-team': {
      id: '/blue-team'
      path: '/blue-team'
      fullPath: '/blue-team'
      preLoaderRoute: typeof BlueTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esc/$escId': {
      id: '/esc/$escId'
      path: '/esc/$escId'
      fullPath: '/esc/$escId'
      preLoaderRoute: typeof EscEscIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlueTeamRoute: BlueTeamRoute,
  BorradorGlassRoute: BorradorGlassRoute,
  CheatSheetRoute: CheatSheetRoute,
  DecisionRoute: DecisionRoute,
  MapaRoute: MapaRoute,
  ParcheRoute: ParcheRoute,
  PracticaRoute: PracticaRoute,
  TablaRoute: TablaRoute,
  EscEscIdRoute: EscEscIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
